#:schema node_modules/wrangler/config-schema.json
name = "electrical-hall-nig-ltd"
compatibility_date = "2024-04-01"

[vars]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "electrical-hall-db"
database_id = "90b4bd38-f07d-4236-8264-b2ba97b39f6f"
